name: publish pages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: build
      run: |
        make
        touch _site/.nojekyll
        ls ${{ github.workspace }}/_site
    
    - name: publish
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2 
      with:
        dir: _site
        branch: gh-pages
        token: ${{ secrets.PUSH_TOKEN }}