name: publish pages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: build
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
        pip install pandoc
        echo '{"site_url": "https://simonm3.github.io/makesite/"}' > params.json
        make
        touch .nojekyll
    
    - name: publish
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2 
      with:
        dir: _site
        branch: gh-pages
        token: ${{ secrets.PUSH_TOKEN }}